parameters:
- name: platform
  type: string
  values:
  - win-x64
  - linux-x64
- name: pool
  type: object

jobs:
- job:
  displayName: "[${{ parameters.platform }}] Build, test, and publish BuildToolsInstaller"
  pool: ${{ parameters.pool }}
  variables:
    buildConfiguration: 'Release' 
    artifactName: '1ES.BuildToolsInstaller.${{ parameters.platform }}.v1.zip'

  steps:
  - powershell: |
      // We really want to prevent deploying breaking changes to the original installer location 
      if ("$(artifactName)" -eq "1ES.BuildToolsInstaller.${{ parameters.platform }}.zip") 
      {
        Write-Error "Can't deploy to 1ES.BuildToolsInstaller.${{ parameters.platform }}.zip"
        exit 1
      }
    displayName: Hard fail if we are trying to publish to the original installer location

  - checkout: self
    fetchDepth: 1
    fetchTags: false

  - template: /.azdo/common/use-latest-dotnet-sdk.yml@self

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Private/BuildToolsInstaller'
    displayName: 'Build Project'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'Private/BuildToolsInstaller'
      arguments: '--no-build --configuration $(buildConfiguration)'
    displayName: 'Run Tests'
  
  # We can't use DotNetCoreCLI@2 for publish because it's not possible
  # to target the csproj we care about, it will scan the whole repository
  # and use a random one instead.
  - script: |
      dotnet publish Private/BuildToolsInstaller/src/BuildToolsInstaller.csproj --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/publish
    displayName: 'Publish Project'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifactName)'
      replaceExistingArchive: true
    displayName: 'Archive Build Output'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $storageAccount = "bxlscripts"
        $containerName = '$web'
        $blobName = "$(artifactName)"
        $filePath = "$(Build.ArtifactStagingDirectory)/$(artifactName)"
        $clientId = "b583f84b-187a-44e6-a85a-30e9089292d8" # BuildXL-DevOpsAgents-ConfigUploader-Identity
        # Authenticate using the user-assigned managed identity
        az login --identity --username $clientId
        # Upload the file to blob storage
        az storage blob upload `
          --overwrite `
          --account-name $storageAccount `
          --container-name $containerName `
          --name $blobName `
          --file $filePath `
          --auth-mode login