trigger: none  # Explicitly scheduled

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        image: Windows-SDL-Image
        os: windows

    stages:
    - stage:
      displayName: Test, build and publish
      jobs:
      - template: /.azdo/installer/publish/job.yml@self
        parameters:
          platform: linux-x64
          pool: 
            name: BuildXL-DevOpsAgents-Selfhost-BuildCache
            image: linux-PME-GPT
            os: linux  

      - template: /.azdo/installer/publish/job.yml@self
        parameters:
          platform: win-x64
          pool: 
            name: BuildXL-DevOpsAgents-Selfhost-BuildCache
            os: windows  
            demands: ImageOverride -equals 1ESPT-Win2022-PME-3
