trigger: none # Triggered only by the rolling pipeline

parameters:
- name: rmBranch
  type: string
  default: master
- name: EnablePublishing
  type: boolean
  default: true

variables:
# The internal YAMLs use this value to skip publishing tasks
- name: EnablePublishing
  value: ${{ parameters.EnablePublishing }}

resources:
  repositories:
  # CODESYNC:
  #  [IMPORTANT!] This value (DominoReleaseManagement) must not be changed without
  #               updating all the references to it in the pipeline templates in the RM repository.
  - repository: DominoReleaseManagement
    type: git
    name: Domino.ReleaseManagement
    ref: ${{ parameters.rmBranch }}
  
  pipelines:
  - pipeline: BxlRollingPipeline
    source: '\BuildXL\BuildXL Rolling'
    trigger:
      branches:
        include:
          - main
  - pipeline: CloudBuild
    source: 'CloudBuild\ReleaseBuilds\CloudBuild Deploy QBits (YML)'

extends:
  template: /pipelines/release/pipeline.yml@DominoReleaseManagement
