# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

trigger: none # Explicitly scheduled for PRs

jobs:
- job: buildTests
  displayName: Build Unit Test Deployment with BuildXL on Windows
  pool:
    name: BuildXL-DevOpsAgents-PME
  steps:
  - checkout: self

  - template: ../common/journaling.yml # Enable journaling
  
  - template: /.azdo/common/set-variable-pats.yml
  - script: >-
      bxl.cmd
      /f:output='$(Build.SourcesDirectory)\Out\Bin\Release\tests\*'
      -CacheNamespace BuildXL.MacOS
      -SharedCacheMode ConsumeAndPublish
      /p:[Sdk.BuildXL]microsoftInternal=1
      /q:ReleaseDotNetCoreMac
      /server-
      /logOutput:FullOutputOnWarningOrError
      /ado
      /scrubDirectory:Out\objects
      /cachemiss:[BxlMacOSPRValidation]
    displayName: 'Build MacOS Test Binaries'
    env:
      1ESSHAREDASSETS_BUILDXL_FEED_PAT: $(1ESSHAREDASSETS_BUILDXL_FEED_PAT)
      CLOUDBUILD_BUILDXL_SELFHOST_FEED_PAT: $(CLOUDBUILD_BUILDXL_SELFHOST_FEED_PAT)
      MSENG_GIT_PAT: $(MSENG_GIT_PAT)
      VSTSPERSONALACCESSTOKEN: $(VSTSPERSONALACCESSTOKEN)
      ARTIFACT_CREDENTIALPROVIDERS_PATH: $(ARTIFACT_CREDENTIALPROVIDERS_PATH)
      CLOUDBUILD_BUILDXL_SELFHOST_FEED_PAT_B64: $(CLOUDBUILD_BUILDXL_SELFHOST_FEED_PAT_B64)
      VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: $(VSS_NUGET_EXTERNAL_FEED_ENDPOINTS)

  - task: PublishBuildArtifacts@1
    displayName: Publish Test Binaries
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/Out/Bin/Release/tests'
      ArtifactName: 'macos-tests-$(Build.BuildId)'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    displayName: Publish Build Logs on Failure
    condition: failed() 
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/Out/Logs'
      ArtifactName: 'macos-tests-xunit-logs-$(Build.BuildId)'
      publishLocation: 'Container'

- job: runTests
  dependsOn: buildTests
  displayName: Run Unit Tests with XUnit on MacOS
  pool:
    vmImage: 'macos-latest'
  steps:
  - checkout: self
  
  - task: DownloadBuildArtifacts@1
    displayName: Download Test Binaries
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'macos-tests-$(Build.BuildId)'
      downloadPath: '$(System.ArtifactsDirectory)/tests'
      cleanDestinationFolder: true

  - task: Bash@3
    displayName: Prepare Intermediate Directories
    inputs:
      targetType: 'inline'
      script: |
        mkdir -p $(Agent.TempDirectory)/BuildXLMacOS/InteropLibrary
        rm -rf $(Agent.TempDirectory)/BuildXLMacOS/InteropLibrary/*
      workingDirectory: '$(Agent.TempDirectory)'

  - task: Bash@3
    displayName: Build Debug libBuildXLInterop.dylib
    inputs:
      filePath: '$(Build.SourcesDirectory)/Private/macOS/xcodebuild.sh'
      arguments: '--projectPath $(Build.SourcesDirectory)/Public/Src/Sandbox/MacOs/Interop/Interop.xcodeproj --scheme InteropLibrary --configuration debug --outputDirectory $(Agent.TempDirectory)/BuildXLMacOS/InteropLibrary --bundlePath $(Build.SourcesDirectory)/Public/Src/Sandbox/MacOs/BundleInfo.xcconfig'
      workingDirectory: '$(Agent.TempDirectory)/BuildXLMacOS'

  - task: Bash@3
    displayName: Copy libBuildXLInterop.dylib to test directory
    inputs:
      targetType: 'inline'
      script: 'cp $(Agent.TempDirectory)/BuildXLMacOS/InteropLibrary/Build/Products/debug/libBuildXLInterop.dylib $(System.ArtifactsDirectory)/tests/macos-tests-$(Build.BuildId)/osx-x64/tests/sharedbin/libBuildXLInterop.dylib'
      workingDirectory: '$(Agent.TempDirectory)/BuildXLMacOS/InteropLibrary'

  - task: Bash@3
    displayName: Run Tests
    inputs:
      filePath: '$(System.ArtifactsDirectory)/tests/macos-tests-$(Build.BuildId)/osx-x64/bashrunner.sh'
      workingDirectory: '$(System.ArtifactsDirectory)/tests/macos-tests-$(Build.BuildId)/osx-x64'
      failOnStderr: true
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Test Logs on Failure
    condition: failed() 
    inputs:
      PathtoPublish: '$(System.ArtifactsDirectory)/tests/macos-tests-$(Build.BuildId)/osx-x64/tests/sharedbin/XunitLogs'
      ArtifactName: 'macos-tests-xunit-logs-$(Build.BuildId)'
      publishLocation: 'Container'