# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

trigger: none # Explicitly scheduled for PRs

jobs:
- job: buildTests
  displayName: Build Unit Test Deployment with BuildXL on Windows
  pool:
    name: BuildXL-DevOpsAgents-Selfhost
    os: windows
  steps:
  - checkout: self

  - template: /.azdo/common/journaling.yml # Enable journaling

  - template: /.azdo/common/set-variable-pats.yml

  - script: >-
      bxl.cmd
      /f:output='$(Build.SourcesDirectory)\Out\Bin\Release\tests\*'
      -CacheNamespace BuildXL.MacOS
      -SharedCacheMode ConsumeAndPublish
      /p:[Sdk.BuildXL]microsoftInternal=1
      /q:ReleaseDotNetCoreMac
      /logOutput:FullOutputOnWarningOrError
      /scrubDirectory:Out\objects
      /cachemiss:BxlMacOSPRValidation
    displayName: 'Build MacOS Test Binaries'
    env:
      1ESSHAREDASSETS_BUILDXL_FEED_PAT: $(1ESSHAREDASSETS_BUILDXL_FEED_PAT)
      CLOUDBUILD_BUILDXL_SELFHOST_FEED_PAT: $(CLOUDBUILD_BUILDXL_SELFHOST_FEED_PAT)
      MSENG_GIT_PAT: $(MSENG_GIT_PAT)
      VSTSPERSONALACCESSTOKEN: $(VSTSPERSONALACCESSTOKEN)
      ARTIFACT_CREDENTIALPROVIDERS_PATH: $(ARTIFACT_CREDENTIALPROVIDERS_PATH)
      CLOUDBUILD_BUILDXL_SELFHOST_FEED_PAT_B64: $(CLOUDBUILD_BUILDXL_SELFHOST_FEED_PAT_B64)
      VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: $(VSS_NUGET_EXTERNAL_FEED_ENDPOINTS)

  - task: PublishBuildArtifacts@1
    displayName: Publish Test Binaries
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/Out/Bin/Release/tests'
      ArtifactName: 'macos-tests-$(Build.BuildId)'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    displayName: Publish Build Logs on Failure
    condition: failed() 
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/Out/Logs'
      ArtifactName: 'macos-tests-xunit-logs-$(Build.BuildId)'
      publishLocation: 'Container'

- template: /.azdo/pr/macos-build-native-and-run-tests.yml
  parameters:
    platform: x64

- template: /.azdo/pr/macos-build-native-and-run-tests.yml
  parameters:
    platform: arm64