jobs:
- job: Linux_Internal
  displayName: Linux Internal Build
  timeoutInMinutes: 180
  
  pool:
    name: BuildXL-DevOpsAgents-Linux-Stateless-PME
    os: linux
  
  templateContext:
    outputs:
      - output: artifactsDrop
        displayName: Publish Intermediate Linux Debug/Release binaries to Drop
        dropServiceURI: https://mseng.artifacts.visualstudio.com/DefaultCollection
        buildNumber: BuildXL/Linux/Internal/Intermediate/$(Build.BuildNumber)/$(Build.BuildId)
        sourcePath: $(Build.SourcesDirectory)/Out/Bin
        retentionDays: 1
        dropMetadataContainerName: DropMetadata-Linux-Intermediate-Internal
      
      - output: buildArtifacts
        displayName: Publish build logs
        condition: succeededOrFailed()
        PathtoPublish: $(Build.SourcesDirectory)/Out/Logs/Build
        ArtifactName: linuxbuildlogs-internal
        sbomEnabled: false    # SBOM is not needed for logs

  steps:
  - checkout: self
    fetchDepth: 1
    fetchTags: false
  
  - template: ../steps/linux_prepare.yml
    parameters:
      CacheNamespace: BuildXLSelfhost.Linux

  - task: Bash@3
    displayName: Build new LKG
    inputs:
      targetType: inline
      script: >
        set -eu

        bash bxl.sh --internal --minimal --deploy-dev --release --shared-comp
        /cacheMiss:"[Bxl.Selfhost.Linux]"
        /cacheConfigFilePath:Out/CacheConfig.json
        /logoutput:FullOutputOnError
        /logsDirectory:"Out/Logs/Build"
      workingDirectory: /home/subst
    env:
      PAT1esSharedAssets: $(PAT-TseBuild-AzureDevOps-1esSharedAssets-Package-Read)
      PATCloudBuild: $(PAT-TseBuild-AzureDevOps-CloudBuild-Packaging-Read)
      VSTSPERSONALACCESSTOKEN: $(PAT-TseBuild-AzureDevOps-mseng-buildcache) # TODO [maly]: do we really need this?
  
  - task: Bash@3
    displayName: Build Debug/Release Binaries for Drop/Nuget/NPM using LKG
    inputs:
      targetType: inline
      script: >-
        set -eu

        bash bxl.sh --use-dev --shared-comp --internal
        /cacheMiss:"[Bxl.Selfhost.Linux]"
        /cacheConfigFilePath:Out/CacheConfig.json
        /logoutput:FullOutputOnError
        /logsDirectory:"Out/Logs/Build"
        /p:Build.BuildId=$(Build.BuildNumber)
        /p:[BuildXL.Branding]SourceIdentification=$(Branding_SourceIdentification)
        /q:DebugLinux
        /q:ReleaseLinux
        "/f:output='/home/subst/Out/Bin/*'"
      workingDirectory: /home/subst
    env:
      PAT1esSharedAssets: $(PAT-TseBuild-AzureDevOps-1esSharedAssets-Package-Read)
      PATCloudBuild: $(PAT-TseBuild-AzureDevOps-CloudBuild-Packaging-Read)
      VSTSPERSONALACCESSTOKEN: $(PAT-TseBuild-AzureDevOps-mseng-buildcache) # TODO [maly]: do we really need this?

  - task: Bash@3
    displayName: Run ReleaseLinux unit tests with LKG
    inputs:
      targetType: inline
      script: >-
        set -eu

        bash bxl.sh --use-dev --shared-comp --internal
        /cacheMiss:"[Bxl.Selfhost.Linux]"
        /cacheConfigFilePath:Out/CacheConfig.json
        /logoutput:FullOutputOnError
        /logsDirectory:"Out/Logs/Build"
        /q:ReleaseLinux "/f:tag='test'"
        /p:BUILDXL_FINGERPRINT_SALT="objects-dir"
      workingDirectory: /home/subst
    env:
      PAT1esSharedAssets: $(PAT-TseBuild-AzureDevOps-1esSharedAssets-Package-Read)
      PATCloudBuild: $(PAT-TseBuild-AzureDevOps-CloudBuild-Packaging-Read)
      VSTSPERSONALACCESSTOKEN: $(PAT-TseBuild-AzureDevOps-mseng-buildcache) # TODO [maly]: do we really need this?

  - task: Bash@3
    displayName: Clean bin directory for Drop
    inputs:
      targetType: inline
      script: |
        set -eu
        rm -rf Out/Bin/debug/sdk
        rm -rf Out/Bin/release/sdk
      workingDirectory: /home/subst