jobs:
- job: Linux_Internal
  displayName: Linux Internal Build
  timeoutInMinutes: 180

  pool:
    name: BuildXL-DevOpsAgents-Selfhost-BuildCache
    image: linux-PME-GPT
    os: linux

  templateContext:
    sdl:
      binskim:
        preReleaseVersion: '' # Use old version of binskim for Linux builds, binskim 4.3.1 has issues running on Linux
    outputs:
      - output: artifactsDrop
        displayName: Publish Intermediate Linux Debug/Release binaries to Drop
        dropServiceURI: https://mseng.artifacts.visualstudio.com/DefaultCollection
        buildNumber: BuildXL/Linux/Internal/Intermediate/$(Build.BuildNumber)/$(Build.BuildId)
        sourcePath: $(Build.SourcesDirectory)/Out/Bin
        retentionDays: 1
        dropMetadataContainerName: DropMetadata-Linux-Intermediate-Internal
      
      - output: buildArtifacts
        displayName: Publish build logs
        condition: succeededOrFailed()
        PathtoPublish: $(Build.SourcesDirectory)/Out/Logs/Build
        ArtifactName: linuxbuildlogs-internal
        sbomEnabled: false    # SBOM is not needed for logs

  steps:
  - checkout: self
    fetchDepth: 1
    fetchTags: false

  - template: ../steps/linux_prepare.yml
    parameters:
      CacheNamespace: BuildXLSelfhost.Linux

  - task: Bash@3
    displayName: Build new LKG
    inputs:
      targetType: inline
      script: >
        set -eu

        bash bxl.sh --internal --minimal --deploy-dev --release --shared-comp
        /cacheMiss:Bxl.Selfhost.Linux
        /cacheConfigFilePath:Out/CacheConfig.json
        /logoutput:FullOutputOnError
        /logsDirectory:"Out/Logs/Build"
      workingDirectory: /home/subst
    env:
      PAT1esSharedAssets: $(BuildXL-Pipeline-AccessToken)
      PATCloudBuild: $(BuildXL-Pipeline-AccessToken)
      VSTSPERSONALACCESSTOKEN: $(System.AccessToken)

  # Acquire another token because the previous one may have been expired.
  - template: /.azdo/common/generate-access-token.yml
    parameters:
      AccessTokenVariable: BuildXL-Pipeline-AccessToken

  - task: Bash@3
    displayName: Build Debug/Release Binaries for Drop/Nuget/NPM using LKG
    inputs:
      targetType: inline
      script: >-
        set -eu

        bash bxl.sh --use-dev --shared-comp --internal
        /cacheMiss:Bxl.Selfhost.Linux
        /cacheConfigFilePath:Out/CacheConfig.json
        /logoutput:FullOutputOnError
        /logsDirectory:"Out/Logs/Build"
        /p:Build.BuildId=$(Build.BuildNumber)
        /p:[BuildXL.Branding]SourceIdentification=$(Branding_SourceIdentification)
        /q:DebugLinux
        /q:ReleaseLinux
        /q:DebugLinuxNet9
        /q:ReleaseLinuxNet9
        "/f:output='/home/subst/Out/Bin/*'ortag='test'"
      workingDirectory: /home/subst
    env:
      PAT1esSharedAssets: $(BuildXL-Pipeline-AccessToken)
      PATCloudBuild: $(BuildXL-Pipeline-AccessToken)
      VSTSPERSONALACCESSTOKEN: $(System.AccessToken)

  # Delete all linux outputs that aren't eventually published to save SDL scanning costs
  # This leaves out/bin/release/npm and out/bin/release/pkgs which eventually get published
  # Still build everything for sake of ensuring it still builds
  - task: Bash@3
    displayName: Clean bin directory for Drop
    inputs:
      targetType: inline
      script: |
        set -eu
        rm -rf Out/Bin/debug
        rm -rf Out/Bin/Demos
        rm -rf Out/Bin/net8.0
        rm -rf Out/Bin/release/cache
        rm -rf Out/Bin/release/ide
        rm -rf Out/Bin/release/linux-x64
        rm -rf Out/Bin/release/tools
        du -h --max-depth=4 Out/Bin
      workingDirectory: /home/subst