jobs:
- job: PublishBinaries
  displayName: 'AzDev Hosted: Publish build binaries'
  timeoutInMinutes: 240
  dependsOn:
  pool:
    name: BuildXL-DevOpsAgents-PME
    os: windows

  templateContext:
    outputParentDirectory: $(Agent.TempDirectory)/DownloadedDrop
    outputs:
    - output: artifactsDrop
      displayName: Publish BuildXL to mseng Artifact Services Drop (mseng.visualstudio.com)
      dropServiceURI: https://mseng.artifacts.visualstudio.com/DefaultCollection
      buildNumber: buildxl.dogfood.$(Build.BuildNumber)  
      sourcePath: $(Agent.TempDirectory)/DownloadedDrop
      detailedLog: true
      retentionDays: 180
      dropMetadataContainerName: DropMetadata-mseng
      sbomEnabled: false
    
    - output: artifactsDrop
      displayName: Publish BuildXL to CB Artifact Services Drop (cloudbuild.visualstudio.com)
      dropServiceURI: https://cloudbuild.artifacts.visualstudio.com/DefaultCollection
      buildNumber: buildxl.dogfood.$(Build.BuildNumber)
      sourcePath: $(Agent.TempDirectory)/DownloadedDrop
      detailedLog: true
      usePat: false
      retentionDays: 180
      dropMetadataContainerName: DropMetadata-cloudbuild
      sbomEnabled: false

    - output: nuget
      displayName: Push private nuget packages to feed
      packageParentPath: $(Agent.TempDirectory)/DownloadedDrop/release/private/pkgs 
      packagesToPush: $(Agent.TempDirectory)/DownloadedDrop/release/private/pkgs/*.nupkg
      nuGetFeedType: external
      publishFeedCredentials: 1924030c-ebba-4483-ada7-b3a1aa99ee84 # BuildXL__PAT-TseBuild-AzureDevOps-1EsSharedAssets__BuildXL.Internal @ 1essharedassets
      sbomEnabled: false
  
    - output: nuget
      displayName: Push public nuget packages to feed
      condition: and(succeeded(), ne(variables['ServicingOnlyBuild'], 'true'))
      packageParentPath: $(Agent.TempDirectory)/DownloadedDrop/release/pkgs 
      packagesToPush: $(Agent.TempDirectory)/DownloadedDrop/release/pkgs/*.nupkg
      nuGetFeedType: external
      publishFeedCredentials: bad95911-cdf1-4bad-9311-99b0848872d4 # BuildXL__PAT-TseBuild-AzureDevOps-1EsSharedAssets__BuildXL 1essharedassets public feed
      sbomEnabled: false
  
  steps:     
  - checkout: self  # We need this to call the SBOM validation script
    fetchDepth: 1
    fetchTags: false

  # Set PAT to pull from CB
  - template: ../../common/set-artifacts-pat.yml
    parameters:
      AzDevPAT: $(PAT-TseBuild-AzureDevOps-CloudBuild)

  - task: ms-vscs-artifact.build-tasks.artifactDropDownloadTask-1.artifactDropDownloadTask@0
    displayName: Download candidate BuildXL
    inputs:
      dropMetadataContainerName: SecondBuildFull
      dropServiceURI: ''
      destinationPath: $(Agent.TempDirectory)/DownloadedDrop
      usePat: false

  - task: AzureArtifacts.drop-validator-task.drop-validator-task.DropValidatorTask@0
    displayName: Drop Validator (Build Manifest Validation)
    inputs:
      BuildDropPath: $(Agent.TempDirectory)/DownloadedDrop
      OutputPath: $(Agent.TempDirectory)/Output
      ValidateSignature: true
      Verbosity: Verbose

  - task: PowerShell@2
    displayName: Print Drop Validator Result
    inputs:
      targetType: inline
      script: get-content $(Agent.TempDirectory)/Output
      errorActionPreference: continue
  
  - task: PowerShell@2
    displayName: SBOM Validation
    inputs:
      filePath: Shared/Scripts/SBOMValidation.ps1
      arguments: -SBOMManifestFile  $(Agent.TempDirectory)/DownloadedDrop/_manifest/spdx_2.2/manifest.spdx.json -BcdeOutputFile  $(Agent.TempDirectory)/DownloadedDrop/_manifest/bcde-output.json

  # Set PAT to pull from mseng
  - template: ../../common/set-artifacts-pat.yml
    parameters:
      AzDevPAT: $(PAT-TseBuild-AzureDevOps-MsEng)

  # Add MacOS and Linux artifacts to the DownloadedDrop directory, so they will be included in the
  # final drop produced by this pipeline. This way the release pipeline has everything it needs in
  # a single drop.

  - task: ms-vscs-artifact.build-tasks.artifactDropDownloadTask-1.artifactDropDownloadTask@0
    displayName: Download MacOS Runtime Nuget Package
    inputs:
      dropMetadataContainerName: DropMetadata-MacOS-Intermediate
      dropServiceURI: ''
      destinationPath: $(Agent.TempDirectory)/DownloadedDrop
      usePat: false

  - task: ms-vscs-artifact.build-tasks.artifactDropDownloadTask-1.artifactDropDownloadTask@1
    displayName: Download Internal Linux Intermediate Artifacts
    inputs:
      dropMetadataContainerName: DropMetadata-Linux-Intermediate-Internal
      dropServiceURI: ''
      destinationPath: $(Agent.TempDirectory)/DownloadedDrop
      usePat: false

  # Set PAT to be able to publish to CB artifact feed. That step is injected by 1ESPT
  - template: ../../common/set-artifacts-pat.yml
    parameters:
      AzDevPAT: $(PAT-TseBuild-AzureDevOps-CloudBuild)
  
- job: GitHubForcePush
  displayName: Force Push BuildXL.Internal to GitHub Main
  timeoutInMinutes: 180
  # Only force push the main branch
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  pool:
    name: BuildXL-DevOpsAgents-PME
    os: windows

  steps:
  - checkout: self
    fetchTags: true
  
  - task: DownloadSecureFile@1
    name: File_Known_Hosts
    displayName: Download secure file
    inputs:
      secureFile: buildxl_github_known_hosts
  
  - task: PowerShell@2
    displayName: Force push to GitHub master SSH
    inputs:
      filePath: Shared/Scripts/github/PushToGHWithDeployKey.ps1
      arguments: '"$(Key-Github-DeployKey-PrivateKey)" "$(Key-Github-DeployKey-PublicKey)" "$(File_Known_Hosts.secureFilePath)"'
