trigger: none

pool:
  name: BuildXL-DevOpsAgents-PME

resources:
  repositories:
    - repository: DominoReleaseManagement
      type: git
      name: Domino.ReleaseManagement
    - repository: CloudBuild
      type: git
      name: CloudBuild

stages:
- stage:
  variables:
  - group: "BuildXL Secrets"
  jobs:
    - job: UpdateSBOMPackages
      displayName: "Update SBOM Packages"
      steps:
      - checkout: self
        persistCredentials: true
      - checkout: DominoReleaseManagement
      - checkout: CloudBuild
      - template: ../common/use-latest-dotnet-sdk.yml

      # Nuget authenticate is required for package restore to work even though the feed is under the same organization as the pipeline
      - task: NuGetAuthenticate@1
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '$(Build.SourcesDirectory)/Domino.ReleaseManagement/src/BuildXLReleaseManagement/BuildXLReleaseManagement/BuildXLReleaseManagement.csproj'
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: false
      - template: ../common/journaling.yml # Enable journaling
      - template: ../common/generate-access-token.yml
        parameters:
          ServiceConnection: 'mseng-Domino-BuildXL-Pipelines'
          Resource: 'https://cloudbuild.microsoft.com/'
          AccessTokenVariable: 'CloudBuildAccessToken'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: .\BuildXLReleaseManagement.exe updatePackages --Packages Microsoft.SBOMCore@latest@1essharedassets@Packaging@$(PAT-TseBuild-AzureDevOps-1EsSharedAssets) Microsoft.Parsers.ManifestGenerator@latest@1essharedassets@Packaging@$(PAT-TseBuild-AzureDevOps-1EsSharedAssets) Microsoft.Sbom.Parsers.Spdx22SbomParser@latest@nuget.org Microsoft.SBOM.Adapters@latest@nuget.org Microsoft.ManifestInterface@latest@1essharedassets@Packaging@$(PAT-TseBuild-AzureDevOps-1EsSharedAssets) Microsoft.Sbom.Contracts@latest@nuget.org Microsoft.ComponentDetection.Contracts@latest@nuget.org python@latest@nuget.org Microsoft.VisualStudio.Services.Governance.ComponentDetection@latest@mseng@ComponentGovernance@$(PAT-TseBuild-AzureDevOps-MsEng-Package-Read) Microsoft.Sbom.Extensions@latest@nuget.org --OneEsPat $(PAT-TseBuild-AzureDevOps-1EsSharedAssets) --CbPat $(PAT-TseBuild-AzureDevOps-CloudBuild) --MsEngGitPat $(PAT-TseBuild-AzureDevOps-MsEng) --ClientSecret $(CloudBuildAccessToken) --BuildXLSourceRoot "$(Build.SourcesDirectory)/BuildXL.Internal" --CloudbuildSourceRoot "$(Build.SourcesDirectory)/CloudBuild"
          showWarnings: true
          pwsh: false
          workingDirectory: '$(Build.ArtifactStagingDirectory)/BuildXLReleaseManagement'
      # Copy and publish BuildXL log in case it failed during the schedule phase
      - task: CopyFiles@2
        continueOnError: true
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/BuildXL.Internal/Out/Logs'
          Contents: '**/BuildXL.log'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/BuildXLLogs'
      - task: PublishPipelineArtifact@1
        continueOnError: true
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)/BuildXLLogs'
          artifact: '$(Build.BuildId).Logs'
          publishLocation: 'pipeline'

    - job: UpdateNoticeFile
      displayName: "Update NOTICE.txt in BuildXL.Internal"
      steps:
      - checkout: self
        fetchDepth: 1
        persistCredentials: true
      
      # Run component detection to generate NOTICE file in the root of the repo.
      # The generated file will be included in the nuget packages we create and publish in this job 
      # If any of these tasks fail we fall back the the NOTICE.txt already checked in the repository.
      - task: ComponentGovernanceComponentDetection@0
        displayName: Component Detection

      - task: notice@0
        displayName: Generate NOTICE file
        inputs:
          outputfile: $(Build.SourcesDirectory)\BuildXL.Internal\NOTICE.txt
          outputformat: text

      - checkout: DominoReleaseManagement
      - template: ../common/use-latest-dotnet-sdk.yml

      # Nuget authenticate is required for package restore to work even though the feed is under the same organization as the pipeline
      - task: NuGetAuthenticate@1
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '$(Build.SourcesDirectory)/Domino.ReleaseManagement/src/BuildXLReleaseManagement/BuildXLReleaseManagement/BuildXLReleaseManagement.csproj'
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: false

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: .\BuildXLReleaseManagement.exe updateNoticeFile --MsEngGitPat $(PAT-TseBuild-AzureDevOps-MsEng) --BuildXLSourceRoot "$(Build.SourcesDirectory)/BuildXL.Internal"
          showWarnings: true
          pwsh: false
          workingDirectory: '$(Build.ArtifactStagingDirectory)/BuildXLReleaseManagement'