# This pipeline does a clean build of the BuildXL repo as a distributed build
# The BuildXL version to download from drop and use for the build (e.g., 0.1.0-20221026.0)
# should be specified via the queue-time variable $(BuildXLPackageVersion) 
trigger: none   # This pipeline is explicitly scheduled

parameters:
  - name: DropName
    type: string
    default: buildxl.dogfood.$(BuildXLPackageVersion)

variables:
  - group: "BuildXL Common variables"
  - name: Domino.DogfoodPackagePath
    value: $(Build.StagingDirectory)\$(Build.BuildId)\Dogfood
  - name: BuildXL.RepoDirectory
    value: $(Build.Repository.LocalPath)
  - name: BuildXL.LogsDirectory
    value: $(BuildXL.RepoDirectory)\Out\Logs
  - name: BxlScriptArgs
    value: -UseAdoBuildRunner -SharedCacheMode ConsumeAndPublish -Use Dev -DevRoot $(Domino.DogfoodPackagePath)\release\win-x64
  - name: BuildXLArgs
    value: /q:ReleaseNet8 /p:[Sdk.BuildXL]microsoftInternal=1 /p:BUILDXL_FINGERPRINT_SALT=* /dynamicBuildWorkerSlots:2 /p:BuildXLWorkerAttachTimeoutMin=5 /logOutput:FullOutputOnWarningOrError /p:RetryXunitTests=1 /processRetries:3 /traceinfo:valdation=ReleasePipelineDistribution /enableIncrementalFrontEnd- /p:xunitSemaphoreCount=12
  - name: Codeql.Enabled
    value: false
pool:
  name: BuildXL-DevOpsAgents-Selfhost
  os: windows

stages:
- stage: Build
  displayName: Clean selfhost builds
  jobs:
  - template: job.yml
    parameters:
      DropName: ${{ parameters.DropName }}
      Role: Orchestrator

- stage: Workers
  dependsOn: []
  displayName: Distributed workers for Clean selfhost build
  jobs:
  - template: job.yml
    parameters:
      DropName: ${{ parameters.DropName }}
      Role: Worker