parameters:
- name: BxlCommonArgs # We reuse these across jobs like a constant
  type: string
- name: Role
  type: string
  default: SingleMachine
  values:
  - Orchestrator
  - Worker
  - SingleMachine
- name: ValidationName
  type: string

jobs:
- job: Selfhost_${{ parameters.validationName }}
  displayName: Build and Validate Selfhost (${{ parameters.validationName }})

  pool:
    name: BuildXL-DevOpsAgents-Linux-Stateless-PME
    os: linux

  templateContext:
    inputs:
    - input: checkout
      repository: self
      fetchDepth: 1
      
    outputs:
    - output: pipelineArtifact
      targetPath: $(Build.SourcesDirectory)/Out/Logs
      artifactName: BuildXL-Logs.${{ parameters.validationName }}.${{ parameters.Role }}.$(System.JobName).$(System.JobAttempt)
      condition: always()
      continueOnError: true
      displayName: Upload BuildXL Logs
    sdl:
      credscan:
        enabled: false
      antimalwareScan:
        enabled: false
      publishLogs:
        enabled: false

  timeoutInMinutes: 90

  steps:
  - template: build-selfhost-base.yml
    parameters:
      cacheUniverse: bxlselfhostpublic
      writeCacheConfigFile: true
      buildSteps:
      # 1. Bootstrap public bits
      - bash: |
          set -eu
          # Set a 60m timeout so we can catch hangs *and* get logs collected at the same time. Otherwise the whole job will timeout (check 'timeoutInMinutes' above).
          timeout --signal 9 60m bash bxl.sh /logsDirectory:"Out/Logs/Build" --minimal --deploy-dev --release /forceAddExecutionPermission- /cacheConfigFilePath:Out/CacheConfig.json ${{ parameters.BxlCommonArgs }}
        displayName: Build
        workingDirectory: /home/subst

      # 2. Run tests with the public bits
      - bash: |
          set -eu
          # - the disks on Azure Pipeline VMs are too small to build everything, so let's instead run tests
          # Set a 60m timeout so we can catch hangs *and* get logs collected at the same time. Otherwise the whole job will timeout (check 'timeoutInMinutes' above).
          timeout --signal 9 60m ./bxl.sh --use-dev --use-adobuildrunner --runner-arg /cacheConfigUniverse:bxlselfhostpublic ${{ parameters.BxlCommonArgs }} /logsDirectory:"Out/Logs/${{ parameters.validationName }}" /q:ReleaseLinux "/f:tag='test'" /logToKusto /cacheLogToKusto /logToKustoBlobUri:https://adomessages.blob.core.windows.net/adomessages /logToKustoIdentityId:6e0959cf-a9ba-4988-bbf1-7facd9deda51 /logToKustoTenantId:975f013f-7f24-47e8-a7d3-abc4752bf346 /dynamicBuildWorkerSlots:0
        displayName: Test (${{ parameters.validationName }})
        workingDirectory: /home/subst
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          AdoBuildRunnerInvocationKey: LinuxSelfhostPublicValidation
          AdoBuildRunnerWorkerPipelineRole: Orchestrator

      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFormat: XUnit
          testResultsFiles: 'Out/Objects/**/xunit-logs/**/xunit*.xml'
        condition: always()
        continueOnError: true