parameters:
- name: BxlCommonArgs # We reuse these across jobs like a constant
  type: string

- name: pool
  type: object
  default:
    name: BuildXL-DevOpsAgents-Linux-Stateless-PME
    os: linux


jobs:
- template: job-build-selfhost-base.yml
  parameters:
    validationName: PTrace
    cacheUniverse: bxlselfhostptrace
    internal: true
    publishTestResults: true
    pool: ${{ parameters.pool }}
    
    buildXLArguments: >-
      --minimal
      --use-dev 
      ${{ parameters.BxlCommonArgs }}
      /cacheMiss:"[Bxl.Selfhost.Linux.PTrace]" 
      /forceEnableLinuxPTraceSandbox+
      /injectCacheMisses:0.3
    preBuildSteps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: current
        artifactName: Dev
        # Use the path that --deploy-dev would use, because we --use-dev in the validation
        targetPath: "$(Build.SourcesDirectory)/Out/Selfhost/Dev"
      displayName: Download BuildXL