parameters:
- name: BxlCommonArgs # We reuse these across jobs like a constant
  type: string

- name: pool
  type: object
  default:
    name: BuildXL-DevOpsAgents-Selfhost-BuildCache
    image: ubuntu-22.04-PME-GPT
    os: linux

- name: sdkVersion
  type: string
  default: '9.x'

# Pre-build steps, including downloading BuildXL if needed
- name: preBuildSteps
  type: stepList
  default: []

jobs:
- template: job-build-selfhost-base.yml
  parameters:
    validationName: InternalRelease
    internal: true
    publishTestResults: true
    pool: ${{ parameters.pool }}
    sdkVersion: ${{ parameters.sdkVersion }}
    distribution:
      enabled: true
      workerCount: 1
    buildXLArguments: >-
      --use-dev
      /q:ReleaseLinux
      ${{ parameters.BxlCommonArgs }}
      "/f:tag='test'"
    
    preBuildSteps:
    # Get bootstrap
    - task: DownloadPipelineArtifact@2
      displayName: 'Download bootstrap'
      inputs:
        artifactName: Dev
        # Use the path that --deploy-dev would use, because we --use-dev in the validation
        targetPath: "$(Build.SourcesDirectory)/Out/Selfhost/Dev"
    - task: Bash@3
      displayName: 'Cleanup pinned BPF maps'
      inputs:
        targetType: 'inline'
        script: |
          # Remove pinned maps and other BPF artifacts; tolerate failures
          # We do this in case the LKG left some pinned maps that are incompatible with the current running daemon
          sudo find /sys/fs/bpf -mindepth 1 -maxdepth 1 -exec rm -rf {} \; || true

    - ${{ each step in parameters.preBuildSteps }}:
      - ${{ step }}
