parameters:
# The provided pool is expected to have at least one build cache associated to it
- name: pool
  type: object
  default:
    name: BuildXL-DevOpsAgents-Selfhost-BuildCache
    image: ubuntu-22.04-PME-GPT
    os: linux

- name: BxlDistributedArgs
  type: string
  default: '
    /c:/home/subst/Private/AdoDistributionTests/config.dsc
    /p:BUILDXL_FINGERPRINT_SALT=*
    /p:BUILDXL_GRAPH_FINGERPRINT_SALT=*
    /replicateOutputsToWorkers+ 
    /p:BuildXLMinimumWaitForRemoteWorkerMin=5
  '

# Pre-build steps, including downloading BuildXL if needed
- name: preBuildSteps
  type: stepList
  default: []

jobs:
- job: TestDistributed
  displayName: Test distributed build

  pool: ${{ parameters.pool }}

  variables:
    - name: BootstrapLocation
      value: $(System.DefaultWorkingDirectory)/Bootstrap

  timeoutInMinutes: 20

  templateContext:
    workflow: BuildXL
    distribution:
      enabled: true
      workerCount: 1
    cache:
      # No cache configuration is needed (besides logging the generated conf for debugging purposes).
      # The pool running this job is expected to have at least one build cache associated to it, so
      # unless specified otherwise, this build will be using it by default
      logGeneratedConfiguration: true
    
    # Pre-build steps: get the engine & prepare workspace
    preBuildSteps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: current
        artifactName: Dev
        targetPath: $(BootstrapLocation)
      displayName: Download BuildXL

    - bash: |
        sudo mkdir /home/subst
        sudo mount --verbose --bind $(Build.SourcesDirectory) /home/subst
      displayName: Bind /home/subst to sources directory  

    - bash: |
        set -eu
        chmod +x $(BootstrapLocation)/AdoBuildRunner
        chmod +x $(BootstrapLocation)/bxl
      displayName: Set execution bits
    
    - ${{ each step in parameters.preBuildSteps }}:
      - ${{ step }}
    
    # Build parameters
    buildXL:
      # We don't use the automatic installation for selfhost builds
      install: false
      invocationPrefix: $(BootstrapLocation)/AdoBuildRunner
      arguments: ${{ parameters.BxlDistributedArgs }}
      env:
        TRANSFORMERS_SDK_DIR: /home/subst/Public/Sdk/Public/Transformers
        OUTPUT_DIR: /home/subst/Out