parameters:
- name: BxlCommonArgs # We reuse these across jobs like a constant
  type: string

- name: pool
  type: object
  default:
    name: BuildXL-DevOpsAgents-Linux-Stateless-PME
    os: linux


jobs:
- template: job-build-selfhost-base.yml
  parameters:
    validationName: InternalRelease
    internal: true
    publishTestResults: true
    pool: ${{ parameters.pool }}
    distribution:
      enabled: true
      workerCount: 1
    buildXLArguments: >-
      --use-dev
      /q:ReleaseLinux
      ${{ parameters.BxlCommonArgs }}
      "/f:tag='test'"
      /logToKusto
      /cacheLogToKusto
      /logToKustoBlobUri:https://adomessages.blob.core.windows.net/adomessages
      /logToKustoIdentityId:6e0959cf-a9ba-4988-bbf1-7facd9deda51
    
    preBuildSteps:
    # Get bootstrap
    - task: DownloadPipelineArtifact@2
      displayName: 'Download bootstrap'
      inputs:
        artifactName: Dev
        # Use the path that --deploy-dev would use, because we --use-dev in the validation
        targetPath: "$(Build.SourcesDirectory)/Out/Selfhost/Dev"
