trigger: none  # Explicitly scheduled for PRs

resources:
  repositories:
  # Temporarily use the private repo until buildJob with BuildXL gets released 
  # - repository: 1esPipelines
  #   type: git
  #   name: 1ESPipelineTemplates/1ESPipelineTemplates
  #   ref: refs/tags/release
  - repository: 1ESPipelines
    type: git
    name: Domino/1ESPipelines
    ref: main

parameters:
- name: BuildSelfhost
  type: boolean
  default: true
- name: BxlCommonArgs
  type: string
  # We pass xunit semaphore `/p:[Sdk.BuildXL]xunitSemaphoreCount=8` to limit the number of parallel xunit pips.
  # Too many xunit pips running in parallel can cause the long running ones to hang. 
  default: '
    /logObservedFileAccesses 
    /logoutput:FullOutputOnError 
    /p:[Sdk.BuildXL]xunitSemaphoreCount=8 
    /forceAddExecutionPermission-
  '
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: BuildXL-DevOpsAgents-Linux-Stateless-PME
      os: linux
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        image: Windows-SDL-Image
        os: windows

    stages:
    - stage: Bootstrap_Internal
      displayName: Bootstrap engine for validations
      dependsOn: []
      jobs:
      # Build and test selfhost with BuildXL
      - template: /.azdo/linux/job-bootstrap.yml@self
        parameters:
          BxlCommonArgs: --shared-comp ${{ parameters.BxlCommonArgs }}
    
    - stage: Build_External
      displayName: External validation
      dependsOn: []
      jobs:
        - template: /.azdo/linux/job-external.yml@self
          parameters:
            BxlCommonArgs: --shared-comp ${{ parameters.BxlCommonArgs }}

    - stage: Build_Internal
      displayName: Internal validation
      dependsOn: Bootstrap_Internal
      jobs:
      - template: /.azdo/linux/job-selfhost.yml@self
        parameters:
          BxlCommonArgs: --shared-comp ${{ parameters.BxlCommonArgs }}

    - stage: Verify_PTrace
      displayName: PTrace validation
      dependsOn: Bootstrap_Internal  
      jobs:
      - template: /.azdo/linux/job-ptrace.yml@self
        parameters:
          BxlCommonArgs: ${{ parameters.BxlCommonArgs }}
    
    - stage: Build_Distributed
      displayName: Distributed test
      dependsOn: [Build_Internal, Verify_PTrace] 
      jobs:
      - template: /.azdo/linux/job-distributed-1espt.yml@self