trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - Documentation
    - Examples
  
variables:
# [NOTE]: We intentionally not include the "BuildXL Secrets" variable group here,
#         and rather do it individually for every job that actually requires it:
#         we especially want to avoid the external validations to access those secrets,
#         which give access to internal resources.
- group: "BuildXL Common variables"
- template: variables.yml
- name: isPublishingBranch
  # We only want to run the publishing stage for main and releases/* branch
  # This condition is to avoid publishing binaries from test runs of the pipeline from custom branches
  value: $[ or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/releases')) ]

resources:
  repositories:
  - repository: 1ESPipelines
    type: git
    name: Domino/1ESPipelines
    ref: main

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: BuildXL-DevOpsAgents-PME
      os: windows
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        image: Windows-SDL-Image
        os: windows
      spotBugs:
        enabled: false
      codeql:
        compiled:
          enabled: false
          justificationForDisabling: 'CodeQL would not be effective on this pipeline because builds are incremental. We will create a separate clean build pipeline for CodeQL.'

    stages:
    - stage: prepare
      displayName: Set build number
      dependsOn: []
      jobs:
      - template: .azdo/rolling/jobs/set-build-number.yml@self

    - stage: CB
      displayName: CB Validation
      dependsOn: prepare
      jobs:
      - template: .azdo/rolling/jobs/cb.yml@self

    - stage: RCIT
      displayName: RunCheckInTests
      variables:
      - group: "BuildXL Secrets"
      dependsOn: prepare
      jobs:
      - template: .azdo/rolling/jobs/run-checkin-tests.yml@self

    - stage: Linux
      displayName: Linux
      variables:
       - group: "BuildXL Secrets"
      dependsOn: prepare
      jobs:
      - template: .azdo/rolling/jobs/linux.yml@self

    - stage: External
      displayName: Build and validate external bits
      dependsOn: prepare
      variables:
        BuildXL.SemanticVersion: $[ stageDependencies.prepare.SetBuildNumber.outputs['SetBuildNumber.BuildXLSemanticVersion'] ]
        BuildXL.PreReleaseTag: $[ stageDependencies.prepare.SetBuildNumber.outputs['SetBuildNumber.BuildXLPreReleaseTag'] ]
      jobs:
      - template: .azdo/rolling/jobs/external.yml@self

    - stage: Mac
      displayName: Mac
      dependsOn: prepare
      jobs:
      - template: .azdo/rolling/jobs/mac.yml@self
    
    - stage: publish
      displayName: Publish
      variables:
      - group: "BuildXL Secrets"
      dependsOn: [CB, RCIT, External, Linux, Mac]
      condition: and(succeeded(), eq(variables.isPublishingBranch, true))
      jobs:
      - template: .azdo/rolling/jobs/publish.yml@self
